# Site settings
author: Madeline Stark
title: Madeline Makes Things
header-img: img/home-bg.png
email: madeline.stark1@gmail.com
copyright_name: Madeline Stark
description: > # this means to ignore newlines until "baseurl:"
  My exploration of Ruby on Rails and JavaScript 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Madeline-Stark

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
